"""
Nexearch — Analyzed Post Model
Stores deep LLM analysis results for each scraped post.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Integer, Float, Text, DateTime, Index
)
from app.db.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class NexearchAnalyzedPost(Base):
    """Deep content analysis of a single post, generated by Agent 2."""
    __tablename__ = "nexearch_analyzed_posts"

    id = Column(String, primary_key=True, default=_uuid)
    post_id = Column(String(500), nullable=False, index=True)
    client_id = Column(String, nullable=False, index=True)

    # ── Full Analysis (JSONB-equivalent) ──────────────────────
    analysis_json = Column(Text, nullable=False, default="{}")
    # Contains the complete AnalyzedPost schema as JSON:
    # hook{}, caption_structure{}, content_analysis{},
    # audience_psychology{}, hashtag_analysis{}, timing_analysis{},
    # audio_analysis{}, competitive_signals{}

    # ── Denormalized Fields (for fast querying) ───────────────
    hook_type = Column(String(50), nullable=True)
    hook_strength_score = Column(Integer, default=0)
    primary_topic = Column(String(200), nullable=True)
    secondary_topics = Column(Text, default="[]")  # JSON array
    content_category = Column(String(50), nullable=True)
    primary_emotional_trigger = Column(String(100), nullable=True)
    caption_length_category = Column(String(20), nullable=True)
    format_effectiveness = Column(Integer, default=0)
    uniqueness_score = Column(Integer, default=0)
    authenticity_score = Column(Integer, default=0)
    pacing_style = Column(String(30), nullable=True)
    visual_energy = Column(String(20), nullable=True)

    # ── CTA Analysis ──────────────────────────────────────────
    has_cta = Column(Integer, default=0)  # Boolean as int for SQLite compat
    cta_type = Column(String(100), nullable=True)
    cta_strength = Column(Integer, nullable=True)

    # ── Engagement Context ────────────────────────────────────
    engagement_rate = Column(Float, default=0.0)
    scroll_stop_mechanism = Column(String(500), nullable=True)
    shareability_reason = Column(String(500), nullable=True)

    # ── Writing Quality Analysis ──────────────────────────────
    title_quality_score = Column(Integer, nullable=True)  # 0-100
    description_quality_score = Column(Integer, nullable=True)  # 0-100
    caption_quality_score = Column(Integer, nullable=True)  # 0-100
    writing_style = Column(String(100), nullable=True)  # "professional", "casual", "storytelling"

    # ── Platform-Specific Analysis ────────────────────────────
    platform = Column(String(50), nullable=True)
    platform_specific_json = Column(Text, default="{}")
    # YouTube: SEO score, keyword density, thumbnail analysis
    # Twitter: thread structure, engagement bait analysis
    # LinkedIn: professional tone score, industry relevance
    # TikTok: trend alignment, duet/stitch potential
    # Instagram: grid aesthetic, story continuation
    # Facebook: group share potential, event relevance

    # ── Metadata ──────────────────────────────────────────────
    analyzed_at = Column(DateTime, default=_utcnow)
    llm_provider_used = Column(String(50), default="")
    analysis_version = Column(String(20), default="1.0")
    analysis_duration_ms = Column(Integer, nullable=True)
    tokens_used = Column(Integer, nullable=True)

    __table_args__ = (
        Index("ix_nexearch_analyzed_hook", "client_id", "hook_type", "content_category"),
        Index("ix_nexearch_analyzed_trigger", "client_id", "primary_emotional_trigger"),
        Index("ix_nexearch_analyzed_quality", "client_id", "uniqueness_score", "authenticity_score"),
    )
