"""
Nexearch — Clip Directive Model
Stores the ClipDirective generated for NexClip's AI pipeline.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Integer, Float, Text, DateTime, Boolean, Index
)
from app.db.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class NexearchClipDirective(Base):
    """ClipDirective generated by Agent 5 for NexClip consumption."""
    __tablename__ = "nexearch_clip_directives"

    id = Column(String, primary_key=True, default=_uuid)
    directive_id = Column(String(100), nullable=False, unique=True, default=_uuid)
    client_id = Column(String, nullable=False, index=True)
    dna_version = Column(String(100), nullable=False)

    # ── Full Directive (JSON) ─────────────────────────────────
    directive_json = Column(Text, nullable=False, default="{}")
    # Contains the complete ClipDirective schema:
    # clip_parameters{}, hook_directive{}, caption_directive{},
    # content_directive{}, avoid_directive{}, publish_settings{}

    # ── Quality Metrics ───────────────────────────────────────
    confidence_score = Column(Float, default=0.0)
    data_basis = Column(Integer, default=0)  # Number of posts the directive is trained on

    # ── NexClip System Prompt Injection ───────────────────────
    nexclip_system_prompt_injection = Column(Text, default="")
    # Complete pre-built system context string ready to inject at the top
    # of NexClip's AI model prompt for this client. Plain English, LLM-ready.

    # ── Writing Directives (for Nex Agent) ────────────────────
    title_writing_directive = Column(Text, default="")  # How to write titles for this client
    description_writing_directive = Column(Text, default="")  # How to write descriptions
    caption_writing_directive = Column(Text, default="")  # How to write captions

    # ── Platform-Specific Directives ──────────────────────────
    platform = Column(String(50), nullable=True)
    platform_specific_directive = Column(Text, default="{}")
    # YouTube: thumbnail style, end screen, cards, SEO keywords
    # Twitter: thread format, poll usage, media mix
    # LinkedIn: article format, professional tone level
    # TikTok: trend hooks, sound selection, effect usage
    # Instagram: grid placement, story CTA, reel format
    # Facebook: share optimization, audience targeting

    # ── Status ────────────────────────────────────────────────
    is_active = Column(Boolean, default=True)
    is_overridden = Column(Boolean, default=False)  # True if admin manually changed fields
    override_fields = Column(Text, default="[]")  # JSON array of overridden field paths
    override_by = Column(String(100), default="")  # "admin" or "arc_agent"

    # ── Timestamps ────────────────────────────────────────────
    generated_at = Column(DateTime, default=_utcnow)
    activated_at = Column(DateTime, nullable=True)
    deactivated_at = Column(DateTime, nullable=True)

    __table_args__ = (
        Index("ix_nexearch_directives_active", "client_id", "is_active"),
    )
