"""
Nexearch — Analyzed Post Schemas
Deep content analysis structures generated by Agent 2.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime


class HookAnalysis(BaseModel):
    """Analysis of the post's opening hook."""
    first_line: str = ""
    hook_type: Optional[str] = None
    # question, contrarian, statistic, story_open, bold_claim, how_to,
    # list_tease, fear, desire, humor, shock, relatable_pain, authority,
    # challenge, curiosity_gap, social_proof, before_after
    hook_strength_score: int = Field(default=0, ge=0, le=100)
    hook_analysis: str = ""
    rewrite_suggestion: Optional[str] = None


class CaptionStructure(BaseModel):
    """Structural analysis of the caption text."""
    total_word_count: int = 0
    line_break_pattern: str = "mixed"
    # dense, punchy_short, mixed, single_block
    uses_emojis: bool = False
    emoji_placement: Optional[str] = None
    # leading, trailing, between_lines, scattered, none
    has_cta: bool = False
    cta_type: Optional[str] = None
    cta_strength: Optional[int] = None
    caption_length_category: str = "short"
    # micro (<10 words), short (10-50), medium (50-150), long (150-300), essay (300+)


class ContentAnalysis(BaseModel):
    """Core content topic and format analysis."""
    primary_topic: str = ""
    secondary_topics: List[str] = []
    content_category: str = "educational"
    # educational, motivational, entertaining, promotional, behind_scenes,
    # testimonial, trend_based, storytelling, controversial, tutorial,
    # personal, news, opinion, how_to, listicle, challenge, duet
    format_effectiveness: int = Field(default=50, ge=0, le=100)
    pacing_style: str = "medium"
    # fast_cut, medium, slow_build, static, n/a
    visual_energy: str = "medium"
    # high, medium, low, n/a


class AudiencePsychology(BaseModel):
    """Psychological analysis of audience engagement drivers."""
    primary_emotional_trigger: str = ""
    secondary_emotional_triggers: List[str] = []
    pain_point_addressed: Optional[str] = None
    desire_addressed: Optional[str] = None
    identity_signal: Optional[str] = None
    scroll_stop_mechanism: str = ""
    shareability_reason: Optional[str] = None


class HashtagAnalysis(BaseModel):
    """Hashtag strategy analysis."""
    total_hashtags: int = 0
    strategy: str = "none"
    # none, niche_only, broad_only, mixed, over_tagged
    relevance_score: int = Field(default=50, ge=0, le=100)


class TimingAnalysis(BaseModel):
    """Posting time analysis."""
    posted_day: str = ""
    posted_hour: int = 0
    timing_quality: str = "average"
    # optimal, good, average, poor
    timing_notes: Optional[str] = None


class AudioAnalysis(BaseModel):
    """Audio/sound analysis for video content."""
    using_trending_audio: bool = False
    audio_relevance: str = "n/a"
    # high, medium, low, n/a


class CompetitiveSignals(BaseModel):
    """Competitive differentiation analysis."""
    uniqueness_score: int = Field(default=50, ge=0, le=100)
    production_quality: str = "medium"
    # high, medium, low, n/a
    authenticity_score: int = Field(default=50, ge=0, le=100)


class WritingQuality(BaseModel):
    """Writing quality analysis for titles, captions, descriptions."""
    title_quality_score: Optional[int] = None
    description_quality_score: Optional[int] = None
    caption_quality_score: Optional[int] = None
    writing_style: Optional[str] = None
    # professional, casual, storytelling, formal, conversational, humorous
    vocabulary_level: Optional[str] = None
    # simple, moderate, advanced
    sentence_variety: Optional[str] = None
    # monotone, varied, highly_varied
    power_words_used: List[str] = []


class PlatformSpecificAnalysis(BaseModel):
    """Platform-specific analysis details."""
    platform: str = ""
    seo_score: Optional[int] = None  # YouTube
    keyword_density: Optional[float] = None  # YouTube
    thumbnail_analysis: Optional[str] = None  # YouTube
    thread_structure: Optional[str] = None  # Twitter
    professional_tone_score: Optional[int] = None  # LinkedIn
    trend_alignment_score: Optional[int] = None  # TikTok
    grid_aesthetic_score: Optional[int] = None  # Instagram
    share_potential_score: Optional[int] = None  # Facebook


class AnalyzedPostSchema(BaseModel):
    """Complete analyzed post structure."""
    post_id: str
    hook: HookAnalysis = HookAnalysis()
    caption_structure: CaptionStructure = CaptionStructure()
    content_analysis: ContentAnalysis = ContentAnalysis()
    audience_psychology: AudiencePsychology = AudiencePsychology()
    hashtag_analysis: HashtagAnalysis = HashtagAnalysis()
    timing_analysis: TimingAnalysis = TimingAnalysis()
    audio_analysis: AudioAnalysis = AudioAnalysis()
    competitive_signals: CompetitiveSignals = CompetitiveSignals()
    writing_quality: WritingQuality = WritingQuality()
    platform_specific: PlatformSpecificAnalysis = PlatformSpecificAnalysis()


class AnalyzedPostResponse(BaseModel):
    """API response for an analyzed post."""
    id: str
    post_id: str
    client_id: str
    hook_type: Optional[str] = None
    hook_strength_score: int = 0
    primary_topic: Optional[str] = None
    content_category: Optional[str] = None
    primary_emotional_trigger: Optional[str] = None
    engagement_rate: float = 0.0
    uniqueness_score: int = 0
    authenticity_score: int = 0
    analyzed_at: Optional[datetime] = None
    llm_provider_used: str = ""

    model_config = {"from_attributes": True}
